name: ML Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run tests
      run: |
        python -m pytest tests/

    - name: Train model
      run: |
        python assignment6.py --mode train
        
    - name: Test saved model
      run: |
        MODEL_FILE=$(ls mnist_model_*_cpu.pth | head -n 1)
        python assignment6.py --mode test --model-path $MODEL_FILE