name: ML Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-model-architecture:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Display Model Summary
      run: |
        echo "Model Architecture Summary"
        echo "========================="
        python -c "
        import torch
        from assignment6 import Net
        model = Net()
        total_params = sum(p.numel() for p in model.parameters())
        trainable_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
        print(f'Total Parameters: {total_params:,}')
        print(f'Trainable Parameters: {trainable_params:,}')
        "
        echo "========================="
        
    - name: Run architecture tests
      run: |
        echo "Running Model Architecture Tests..."
        echo "=================================="
        python -m pytest tests/ -v
        echo "=================================="